### PR TITLE
Add multi select

### PR DESCRIPTION
**Pull request by Jonne**
### Motivation

This feature allows content editors to select multiple products. This can be useful to display a product cluster of hand picked products. 

This was my first encounter with VUE, so bear with me if I did something stupid ;-) 

### Checklist

- [x] Code follows coding conventions held in this repo
- [x] Docs have been updated (if applicable)
- [x] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

**Multi-select**
- Configure the custom element on a content type. 
- Set the multiSelect property to true
- Create a content item based on the content type
- The product selector should be displayed 
- It should be possible to search and select multiple products
- It should be possible to remove selected products individually

**Single-select**
- Configure the custom element on a content type. 
- Set the multiSelect property to false
- Create a content item based on the content type
- The product selector should be displayed 
- It should be possible to search and select only a single product

### CODE REVIEW

**Comment by strizr** [comment]
Hey @Jonne , I tested out the element, it works fine, there is just one small issue I have with it - when having multi-select on, you are able to select the same product more than 1 time. I'm not sure this is intentional, however, when you remove the duplicate product from the list of selected products, it removes all occurrences. It's a small thing, however, I would probably alter it so products cannot be added more than once (if you click it again, nothing happens), or, if adding the same product multiple times was indeed intentional, then the removal should only remove the instance that is clicked, not all of them.

**Comment by Jonne** [comment]
> Hey @Jonne , I tested out the element, it works fine, there is just one small issue I have with it - when having multi-select on, you are able to select the same product more than 1 time. I'm not sure this is intentional, however, when you remove the duplicate product from the list of selected products, it removes all occurrences. It's a small thing, however, I would probably alter it so products cannot be added more than once (if you click it again, nothing happens), or, if adding the same product multiple times was indeed intentional, then the removal should only remove the instance that is clicked, not all of them.

Hi @strizr, good find! I will change it so the same product can only be added once. Thanks

**Comment by Jonne** [comment]
@strizr I've fixed the issue, can this PR be merged?

**Comment by strizr** [comment]
Great, thank you!

**Review by strizr — APPROVED** [review]

**Pull request merged**
